In [133]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [134]:
%run ../Jane/extract_data.py

In [119]:
airqual_data

State     County        City    AQIMean       Date
0      Alabama  Jefferson  Birmingham  12.065635 2013-12-01
1      Alabama  Jefferson  Birmingham  12.899658 2014-01-01
2      Alabama  Jefferson  Birmingham   8.851034 2014-02-01
3      Alabama  Jefferson  Birmingham  13.212881 2014-03-01
4      Alabama  Jefferson  Birmingham  11.379411 2014-04-01
...        ...        ...         ...        ...        ...
42884  Wyoming     Weston   Newcastle   2.548553 2016-06-01
42885  Wyoming     Weston   Newcastle   2.558559 2016-07-01
42886  Wyoming     Weston   Newcastle   1.258537 2016-08-01
42887  Wyoming     Weston   Newcastle   0.539661 2016-09-01
42888  Wyoming     Weston   Newcastle   1.694495 2016-10-01

[42889 rows x 5 columns]

In [126]:
nyc_avg = airqual_data[airqual_data.City=='New York'].groupby('Date').mean().reset_index()
nyc_avg
nyc_avg['State'] = 'New York'
nyc_avg['City'] = 'New York'
nyc_aq = pd.concat((nyc_avg,nyc_avg,nyc_avg))
counties = ['New York']*129+['Kings']*129+['Richmond']*129
nyc_aq['County']= counties
nyc_aq = nyc_aq[['State','County','City','AQIMean','Date']]
x = pd.concat((airqual_data,nyc_aq)).groupby(['Date','State','County']).mean().reset_index()

State    County      City    AQIMean       Date
0    New York  New York  New York  24.638826 2010-01-01
1    New York  New York  New York  23.706344 2010-02-01
2    New York  New York  New York  23.670713 2010-03-01
3    New York  New York  New York  22.261414 2010-04-01
4    New York  New York  New York  20.099075 2010-05-01
..        ...       ...       ...        ...        ...
124  New York  Richmond  New York   8.888885 2020-05-01
125  New York  Richmond  New York   9.836835 2020-06-01
126  New York  Richmond  New York   8.928665 2020-07-01
127  New York  Richmond  New York  11.185330 2020-08-01
128  New York  Richmond  New York  10.808280 2020-09-01

[387 rows x 5 columns]

In [131]:
x = pd.concat((airqual_data,nyc_aq)).groupby(['Date','State','County']).mean().reset_index()

Date  State    County    AQIMean
182   2010-01-01  Texas     Bexar   7.603979
183   2010-01-01  Texas  Brazoria   7.043930
184   2010-01-01  Texas    Dallas  15.442358
185   2010-01-01  Texas    Denton   8.510637
186   2010-01-01  Texas   El Paso  20.684311
...          ...    ...       ...        ...
31007 2020-07-01  Texas     Ellis   0.706337
31008 2020-07-01  Texas      Hunt   2.629183
31009 2020-07-01  Texas   Kaufman   2.222812
31010 2020-07-01  Texas   Navarro  -0.357966
31011 2020-07-01  Texas   Tarrant   3.885092

[2564 rows x 4 columns]

In [98]:
# make sure airqual_data has been transformed by extract_data.py

nyc_avg = airqual_data[airqual_data.City=='New York'].groupby('Date').mean().reset_index()
nyc_avg['State'] = 'New York'
nyc_avg['City'] = 'New York'
nyc_aq = pd.concat((nyc_avg,nyc_avg,nyc_avg))
nyc_aq['County']= counties
nyc_aq = nyc_aq[['State','County','City','AQIMean','Date']]

airqual_data = pd.concat((airqual_data,nyc_aq))

Date    AQIMean     State      City
0 2010-01-01  24.638826  New York  New York
1 2010-02-01  23.706344  New York  New York
2 2010-03-01  23.670713  New York  New York
3 2010-04-01  22.261414  New York  New York
4 2010-05-01  20.099075  New York  New York

In [48]:
aq[aq['County'].isin(['San Francisco'])].City.value_counts()


San Francisco    127
Name: City, dtype: int64

In [ ]:
# SF Metro
counties = ['Alameda County', 'Contra Costa County', 'Marin County', 'Napa County', 'San Mateo County', 
            'Santa Clara County', 'Solano County', 'Sonoma County', 'San Francisco County']
# NY Metro:
counties = ['New York County', 'Bronx County', 'Queens County', 'Kings County', 'Richmond County']
# Greater Austin Metro:
counties = ['Travis County']
# Miami Metro:
counties = ['Miami-Dade County', 'Broward County', 'Palm Beach County']

In [130]:
nyc_zillow = zillow_data[zillow_data.City == 'New York'].copy()
nyc_zipcodes = zillow_data[zillow_data.City == 'New York'].Zipcode.value_counts().reset_index()['index'].to_list()
nyc_airqual = airqual_data[airqual_data['City'] == 'New York'].copy()
nyc_persinc = persinc_data[persinc_data.City == 'New York'].copy()
nyc_census = census_data[census_data.Zipcode.isin(nyc_zipcodes)].copy()

In [131]:
nyc_zillow.drop(['RegionID','Metro'],axis=1,inplace=True)

In [132]:
# we want to drop the zipcode 10069
nyc_zillow = nyc_zillow[nyc_zillow.Zipcode != '10069'].copy()

In [136]:
nyc_zillow[nyc_zillow['Year'] >= 2015]

# nulls_df = df[df['Rent'].isnull()]
# bad_zips = nulls_df['Zipcode'].unique().tolist()
# df = df[df['Zipcode'].isin(bad_zips)==False]

Zipcode      City State           County  SizeRank       Date    Rent  \
96772    10025  New York    NY  New York County         1 2015-01-01  3566.0   
96774    10023  New York    NY  New York County         3 2015-01-01  3413.0   
96778    10002  New York    NY  New York County         7 2015-01-01  3508.0   
96782    11226  New York    NY     Kings County        11 2015-01-01  1876.0   
96783    10467  New York    NY     Bronx County        12 2015-01-01  1442.0   
...        ...       ...   ...              ...       ...        ...     ...   
210249   11416  New York    NY    Queens County      1818 2020-01-01  2184.0   
210251   11436  New York    NY    Queens County      1820 2020-01-01  2057.0   
210257   11366  New York    NY    Queens County      1826 2020-01-01  2185.0   
210259   11109  New York    NY  New York County      1828 2020-01-01  3325.0   
210260   10307  New York    NY  Richmond County      1829 2020-01-01  1536.0   

        Year  
96772   2015  
96774   2015  
96778   2015  
96782   2015  
96783   2015  
...      ...  
210249  2020  
210251  2020  
210257  2020  
210259  2020  
210260  2020  

[9089 rows x 8 columns]

In [5]:
# reshape for better merging
inclvl_moderate = inclvl_data[inclvl_data.income_level_group == 'Moderate'][['Date','Vol']]
inclvl_moderate = inclvl_moderate.rename(columns={'Vol':'Vol_moderate_income'})
inclvl_low = inclvl_data[inclvl_data.income_level_group == 'Low'][['Date','Vol']]
inclvl_low = inclvl_low.rename(columns={'Vol':'Vol_low_income'})
inclvl_data = pd.merge(inclvl_moderate,inclvl_low,on='Date')
inclvl_data.head()

Date  Vol_moderate_income  Vol_low_income
0 2005-01-01         4.578106e+09    7.635135e+08
1 2005-02-01         4.563908e+09    7.558710e+08
2 2005-03-01         4.762458e+09    8.171551e+08
3 2005-04-01         4.744005e+09    7.854169e+08
4 2005-05-01         4.752915e+09    8.289172e+08

In [44]:
df = pd.merge(nyc_zillow, inclvl_data,how='left',on='Date')

In [53]:
nyc_airqual.drop(['State','City'],axis=1,inplace=True)

In [57]:
nyc_airqual # only has data for 2 of the 5 counties :( -> omit :/

County    AQIMean       Date
26386   Bronx  25.555341 2010-01-01
26387   Bronx  24.637082 2010-02-01
26388   Bronx  25.338308 2010-03-01
26389   Bronx  22.618458 2010-04-01
26390   Bronx  21.597693 2010-05-01
...       ...        ...        ...
27068  Queens   8.975915 2020-05-01
27069  Queens   9.439863 2020-06-01
27070  Queens   8.190798 2020-07-01
27071  Queens  11.708356 2020-08-01
27072  Queens  10.805796 2020-09-01

[256 rows x 3 columns]

In [48]:
df = df.merge(nyc_persinc, 'left', on ='Year')

In [141]:
census_data.columns.to_list()[100:]

['poverty',
 'gini_index',
 'housing_units',
 'renter_occupied_housing_units_paying_cash_median_gross_rent',
 'owner_occupied_housing_units_lower_value_quartile',
 'owner_occupied_housing_units_median_value',
 'owner_occupied_housing_units_upper_value_quartile',
 'occupied_housing_units',
 'housing_units_renter_occupied',
 'vacant_housing_units',
 'vacant_housing_units_for_rent',
 'vacant_housing_units_for_sale',
 'dwellings_1_units_detached',
 'dwellings_1_units_attached',
 'dwellings_2_units',
 'dwellings_3_to_4_units',
 'dwellings_5_to_9_units',
 'dwellings_10_to_19_units',
 'dwellings_20_to_49_units',
 'dwellings_50_or_more_units',
 'mobile_homes',
 'housing_built_2005_or_later',
 'housing_built_2000_to_2004',
 'housing_built_1939_or_earlier',
 'median_year_structure_built',
 'married_households',
 'nonfamily_households',
 'family_households',
 'households_public_asst_or_food_stamps',
 'male_male_households',
 'female_female_households',
 'children',
 'children_in_single_female_hh'

In [142]:
acs = census_data[['do_date','total_pop','households','median_age','median_income','income_per_capita','pop_determined_poverty_status',
                  'poverty','gini_index','housing_units','different_house_year_ago_different_city','different_house_year_ago_same_city',
                  'pop_in_labor_force','aggregate_travel_time_to_work','bachelors_degree','employed_pop','unemployed_pop',
                  'employed_arts_entertainment_recreation_accommodation_food','Zipcode']].copy()

In [143]:
# proportion of 


In [144]:
# pct poverty
acs['pct_poverty'] = acs['poverty']/acs['pop_determined_poverty_status']
acs.drop(['poverty','pop_determined_poverty_status'],axis=1,inplace=True)

# estimated number of homes for each household (scarse? or many available?)
acs['housing_availability'] = acs['housing_units']/acs['households']
# estimated number of people per household
acs['home_density'] = acs['total_pop']/acs['households']

acs['pct_employed'] = acs['employed_pop']/acs['pop_in_labor_force']
acs['pct_jobs_nightlife'] = acs['employed_arts_entertainment_recreation_accommodation_food']/acs['employed_pop']
acs['pct_unemployed'] = acs['unemployed_pop']/acs['pop_in_labor_force']

# have moved from somewhere else in the same city
acs['move_within_city'] = acs['different_house_year_ago_same_city']/acs['total_pop']
# have moved to this city from a new city
acs['move_new_city'] = acs['different_house_year_ago_different_city']/acs['total_pop']
acs['avg_commute_time'] = acs['aggregate_travel_time_to_work'] / acs['employed_pop']

acs.drop(['pop_in_labor_force','housing_units','employed_pop','employed_arts_entertainment_recreation_accommodation_food','unemployed_pop',
          'different_house_year_ago_same_city','different_house_year_ago_different_city','aggregate_travel_time_to_work'],axis=1,inplace=True)

# percent of population w/ bachelors degree
acs['pct_college'] = acs['bachelors_degree'] / acs['total_pop']
acs.drop('bachelors_degree',axis=1,inplace=True)

In [149]:
acs.sample(10)

total_pop  households  median_age  median_income  income_per_capita  \
9490        2654        1049        45.1        33363.0            18027.0   
4772        1859         629        55.5        41010.0            18881.0   
15161      40402       15055        33.0        53421.0            26766.0   
17653        699         306        47.6        70147.0            29383.0   
31663        321         163        41.0        44019.0            20830.0   
24979      45895       17227        37.2        70842.0            35323.0   
4697        1131         360        35.0        48214.0            21138.0   
25107      17731        6663        34.8        63414.0            30857.0   
4084        1829        1011        55.8        51738.0            46258.0   
32259        159         101        65.1        51913.0            43443.0   

       gini_index Zipcode  pct_poverty  housing_availability  home_density  \
9490       0.4134   36850     0.254539              1.334604      2.530029   
4772       0.3158   18321     0.091985              1.311606      2.955485   
15161      0.4313   21804     0.176364              1.119296      2.683627   
17653      0.3080   43323     0.022890              1.032680      2.284314   
31663      0.2090   23488     0.239875              1.000000      1.969325   
24979      0.4305   55112     0.095792              1.027631      2.664132   
4697       0.3930   47147     0.160035              1.069444      3.141667   
25107      0.4223   33559     0.120415              1.100855      2.661114   
4084       0.4747   55384     0.061335              1.108803      1.809100   
32259      0.1561   96116     0.000000              2.009901      1.574257   

       pct_employed  pct_jobs_nightlife  pct_unemployed  move_within_city  \
9490       0.915544            0.030422        0.084456          0.013564   
4772       0.948916            0.110930        0.051084          0.000000   
15161      0.932784            0.140935        0.063841          0.073957   
17653      0.959770            0.056886        0.040230          0.001431   
31663      0.954082            0.000000        0.045918          0.000000   
24979      0.952753            0.084588        0.047247          0.016037   
4697       0.975610            0.000000        0.024390          0.000000   
25107      0.939027            0.118875        0.057849          0.029891   
4084       0.965352            0.059406        0.034648          0.008748   
32259      1.000000            0.000000        0.000000          0.000000   

       move_new_city  avg_commute_time  pct_college  
9490        0.036549         30.853778     0.048983  
4772        0.155460               NaN     0.059172  
15161       0.143929         20.405392     0.096975  
17653       0.027182         19.970060     0.055794  
31663       0.000000               NaN     0.028037  
24979       0.133479         19.965713     0.194095  
4697        0.015915               NaN     0.026525  
25107       0.128983         28.821839     0.143252  
4084        0.215965         25.068069     0.202296  
32259       0.000000               NaN     0.000000

In [146]:
acs.drop('do_date',axis=1,inplace=True)

In [82]:
census_feats = acs.drop('Zipcode',axis=1)


In [87]:
census_feats.fillna(0, inplace=True)

In [100]:
census_feats.shape

(149, 16)

In [92]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(census_feats)
census_scaled= scaler.transform(census_feats)

In [96]:
# scaled covariance matrix looks pretty OK
M = np.cov(census_scaled)
print(np.round(M,2))

[[ 0.6  -0.08 -0.06 ... -0.09 -0.35  0.01]
 [-0.08  0.28 -0.17 ...  0.24  0.3   0.07]
 [-0.06 -0.17  0.66 ... -0.26 -0.12 -0.27]
 ...
 [-0.09  0.24 -0.26 ...  0.42  0.37  0.21]
 [-0.35  0.3  -0.12 ...  0.37  0.96  0.08]
 [ 0.01  0.07 -0.27 ...  0.21  0.08  0.22]]


In [117]:
#PCA function from scikit learn

pca = PCA(n_components=16) #Using all features
pca.fit(census_scaled) #pca.fit standardize the data

pca_results = pd.DataFrame(list(enumerate(pca.explained_variance_ratio_)))

In [121]:
pca_results = pca_results.rename(columns = {0:'n_components',1:'explained_var'})

In [123]:
pca_results['n_components'] = pca_results['n_components'] +1
pca_results
# it seems like 2 will be the best

n_components  explained_var
0              1       0.466131
1              2       0.183756
2              3       0.100721
3              4       0.058567
4              5       0.049022
5              6       0.038743
6              7       0.027951
7              8       0.021492
8              9       0.016041
9             10       0.013491
10            11       0.009838
11            12       0.005475
12            13       0.003775
13            14       0.002871
14            15       0.001346
15            16       0.000780

In [127]:
pca = PCA(n_components=2) #Using all features
pca.fit(census_scaled)
pca.explained_variance_ratio_

array([0.46613085, 0.18375562])